Accept=Onartu
Close=Itxi
Price= Prezioa
SelectOption=Aukeratu
Aceptar=Eskaintza onartu

MainGUI.CreateSale= Eskaintza sortu
MainGUI.QuerySales= Eskaintzak konstsultatu
MainGUI.SelectOption=Aukeratu
MainGUI.MainTitle=Merkatua: 
MainGUI.LogIn= Saioa hasi
MainGUI.SignIn= Erregistratu
MainGUI.IntrCu= Email:
MainGUI.IntrCon= Pasahitza:
MainGUI.Eleccion= Erabiltzaile mota aukeratu:
MainGUI.Tipo1= Saltzaile
MainGUI.Tipo2= Erosle
MainGUI.Entrar= Sisteman sartu
MainGUI.Back= Atzera
MainGUI.Reg= Erregistratu
MainGUI.Nom= Izena
MainGUI.AcceptSales= Eskaintzak onartuak
MainGUI.VerCarrito= Ikusi orgatxoa



CreateSaleGUI.Title=Tituloa
CreateSaleGUI.Description=Deskripzioa
CreateSaleGUI.Status=Egoera
CreateSaleGUI.Category=Kategoria
CreateSaleGUI.Price=Prezioa
CreateSaleGUI.PriceMustBeGreaterThan0=ERROR, prezioa 0 baino handiagoa
CreateSaleGUI.ProductCreated=Eskaintza sortuta
CreateSaleGUI.CreateProduct=Sortu Eskaintza
CreateSaleGUI.ErrorNumber=Error, prezioa zenbaki bat izan behar da
CreateSaleGUI.ErrorQuery=Error, datuak falta dira
CreateSaleGUI.LoadPicture=Argazkia igo
CreateSaleGUI.PublicationDate=Argitarapen eguna

QuerySalesGUI.Search=Bilatu
QuerySalesGUI.NoProducts=Ez daude eskaintzak
QuerySalesGUI.Price=Prezioa
QuerySalesGUI.FindProducts=Eskaintzak bilatu
QuerySalesGUI.Products=Eskaintzak (Double-click eskaintza ikusteko)

ShowSaleGUI.Title=Eskaintza xehestasunak
ShowSaleGUI.bontoncomprar= Erosi
ShowSaleGUI.lblcomprar= Nahi den prezioa
ShowSaleGUI.lblResOK= Erosketa ongi burutu da
ShowSaleGUI.lblResFAIL= Sartu baliozko prezio bat


DataAccess.SaleAlreadyExist=ERROR, Eskaintza existizen da
DataAccess.ErrorSaleMustBeLaterThanToday=ERROR, data gaur baino beranduago izan behar da
DataAccess.ErrorFileNotUploadedException=ERROR, Argazkia igo behar da

AcceptSaleGUI.Offer= Eskainitako prezioa

ShowOfferGUI.lblComprador= Eroslea:
ShowOfferGUI.lblPrecio= Eskainitako prezioa:

CarritoGUI.Estado= Egoera
CarritoGUI.Rechazado= Errefusatuta
CarritoGUI.Pendiente= Pending
CarritoGUI.Aceptado= Onartuta

#kailai---------------------------------------------------------------------------------------------------------------

MainGUI.MiCartera= Diru-zorroa

WalletGUI.Title= Nire Diru-zorroa
WalletGUI.SaldoActual= Egungo saldoa: 
WalletGUI.CantidadRecargar= Kargatzeko zenbatekoa: 
WalletGUI.BtnRecargar= Kargatu
WalletGUI.BtnVolver= Atzera

WalletGUI.ColFecha= Data
WalletGUI.ColTipo= Mota
WalletGUI.ColCantidad= Zenbatekoa
WalletGUI.ColDesc= Deskribapena

WalletGUI.MsgExito= Karga arrakastatsua: +
WalletGUI.MsgErrorCero= Errorea: Zenbatekoak 0 baino handiagoa izan behar du.
WalletGUI.MsgErrorNum= Errorea: Sartu baliozko zenbaki bat.


VerCarritoGUI.Search=Bilatu
VerCarritoGUI.NoProducts=Ez daude eskaintzak
VerCarritoGUI.Price=Prezioa
VerCarritoGUI.FindProducts=Eskaintzak bilatu
VerCarritoGUI.Products=Eskaintzak (Double-click eskaintza ikusteko)


